language: php

matrix:
  include:
  - php: 5.6
    env: WP_VERSION=latest

before_install:
- sudo rm -rf ~/.nvm - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
- sudo apt-get install -y nodejs

install:
- composer install --no-interaction
- npm install


before_script:
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- |
  if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
    phpenv config-rm xdebug.ini
  else
    echo "xdebug.ini does not exist"
  fi
- |
  if [[ ! -z "$WP_VERSION" ]] ; then
    bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
    composer global require "phpunit/phpunit=4.8.*|5.7.*"
  fi
- |
  if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
    composer global require wp-coding-standards/wpcs
    phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
  fi

script:
- vendor/bin/phpcs --standard=phpcs.xml ./src
- npm test
