version: '3.1'

services:

  wordpress:
    image: wordpress:5.4
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - .:/var/www/repo
      - ./data/uploads:/var/www/html/wp-content/uploads
      - ./src:/var/www/html/wp-content/plugins/appizy-app-embed

  mysql:
    image: mysql:5.7
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
