version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    ports:
      - 8080:1006
    environment:
      WORDPRESS_DB_PASSWORD: example
    volumes:
      - ..:/var/www/repo
      - ../src:/var/www/html/wp-content/plugins/appizy-app-embed

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

